### ISSUE TITLE
Add support for Esperanto

### ISSUE THREAD

**Issue by inferno986return** [jrgdrs/Wittgenstein#1]
Esperanto uses the following circumflex consonant letters as part of its orthography within the Latin Extended-A block of Unicode:

- Ĉ
- ĉ
- Ĝ
- ĝ
- Ĥ
- ĥ
- Ĵ
- ĵ
- Ŝ
- ŝ

**Comment by jrgdrs** [comment]
Thanks Hal, added the glyphs. 

<img width="997" alt="Bildschirm­foto 2024-01-03 um 11 47 07" src="https://github.com/jrgdrs/Wittgenstein/assets/65910557/e85b2b20-a5e8-4ccc-b30d-c8f115c123d9">

Let me know if this works for you.

**Comment by inferno986return** [comment]
Bonega! It seems that circumflex placement isn't standardised on "ĥ", though I prefer it above the stem. Thanks for adding the support and so quickly too.

<img width="932" alt="image" src="https://github.com/jrgdrs/Wittgenstein/assets/1838420/4ad348ce-d89b-4775-989f-83fec2b7d927">

**Comment by jrgdrs** [comment]
Thank you for the suggestion for improvement. Would that be a solution? Your submitted text does not contain the character, but I found these examples here:

<img width="548" alt="Bildschirm­foto 2024-01-03 um 17 06 38" src="https://github.com/jrgdrs/Wittgenstein/assets/65910557/f8170af3-d3a0-4cdb-a55e-2423b1dfd22a">

**Comment by inferno986return** [comment]
Bending the circumflex looks ugly and I wouldn't recommend it. Literata for example puts the circumflex (capitulo) above the stem of the "ĥ". This to me is the most aesthetically pleasing way to present Esperanto's least-used letter.

<img width="947" alt="image" src="https://github.com/jrgdrs/Wittgenstein/assets/1838420/45cb380d-5486-46a8-a254-092f506b8f10">

Libertinus Serif puts it on the shoulder, which is less appealing but could be used where line spacing is tight.. My solution would be to have stylistic alternates for "ĥ" with the primary glyph being the above stem.

<img width="950" alt="image" src="https://github.com/jrgdrs/Wittgenstein/assets/1838420/06425e76-3c1a-4808-b6af-3661537c57c6">

“Laŭ Ludoviko Zamenhof bongustas freŝa ĉeĥa manĝaĵo kun spicoj.”

**Comment by jrgdrs** [comment]
Many thanks for your support and the examples. I have decided on the solution above the stem and updated it:

<img width="847" alt="Bildschirm­foto 2024-01-03 um 23 58 46" src="https://github.com/jrgdrs/Wittgenstein/assets/65910557/84c3b829-1dca-4710-802f-82d411037047">
