### ISSUE TITLE
Add support for common ligatures such as fi and fl

### ISSUE THREAD

**Issue by inferno986return** [jrgdrs/Wittgenstein#2]
For a body serif font, ligatures such as fi and fl are to be expected as they assist with reading flow.

**Comment by jrgdrs** [comment]
Thanks Hal. Added the requested glyphs:

<img width="689" alt="Bildschirm­foto 2024-01-03 um 12 21 01" src="https://github.com/jrgdrs/Wittgenstein/assets/65910557/d40b91d1-4298-4c6b-bb98-43bfbd1ba847">

**Comment by inferno986return** [comment]
The ligatures also look good and make the body text more friendly. 😊

**Comment by inferno986return** [comment]
While there is room for the expanded ligatures, the essentials are covered here.
