### ISSUE TITLE
Italics

### ISSUE THREAD

**Issue by inferno986return** [jrgdrs/Wittgenstein#3]
The type design has some unusual geometry, so I am intrigued to see how that would translate to italics. Italics would also help the versatility of the font family, particularly when made variable.

**Comment by jrgdrs** [comment]
Yes, that's also in my mind. As the italics needs rework I have not put it into the submission but will work on that. You can get an impression with the specimen I put here

https://github.com/jrgdrs/Wittgenstein/blob/354dfd499ffe764c227fc920a7a76e3b79aa35c8/documentation/Wittgenstein_Specimen.html.pdf
