### ISSUE TITLE
Proportional, tabular and text figures

### ISSUE THREAD

**Issue by inferno986return** [jrgdrs/Wittgenstein#4]
Proportional, tabular and text figures - Text figures in particular would be interesting for this design. Does Wittgenstein support tabular numbers?

**Comment by jrgdrs** [comment]
Old Style Figures and Tabular Figures added

<img width="918" alt="Bildschirm­foto 2024-01-03 um 23 41 43" src="https://github.com/jrgdrs/Wittgenstein/assets/65910557/1565a979-32a7-4a48-bdb6-37f4a2ddc74b">
